api_platform:
    title: HomeCloud API
    description: |
        API de stockage de fichiers et médias personnels.
        Tous les endpoints (sauf `/auth/login` et `/auth/token/refresh`) requièrent un token JWT Bearer.
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
