# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.files_dir: '%kernel.project_dir%/uploads/files'
    app.photos_dir: '%kernel.project_dir%/uploads/photos'
    app.photo_allowed_mime_types:
        - 'image/jpeg'
        - 'image/png'
        - 'image/gif'
        - 'image/webp'
        - 'image/bmp'
        - 'image/svg+xml'
        - 'image/tiff'
        - 'image/x-canon-cr2'
        - 'image/x-canon-crw'
        - 'image/x-nikon-nef'
        - 'image/x-sony-arw'
        - 'image/x-adobe-dng'
        - 'image/x-olympus-orf'
        - 'image/x-panasonic-raw'
        - 'image/x-fuji-raf'
        - 'image/x-pentax-pef'
        - 'image/x-samsung-srw'
        - 'image/x-minolta-mrw'
        - 'image/x-leaf-mos'
        - 'image/x-hasselblad-3fr'
        - 'image/x-hasselblad-fff'
        - 'image/x-kodak-dcr'
        - 'image/x-kodak-k25'
        - 'image/x-kodak-kdc'
        - 'image/x-mamiya-mef'
        - 'image/x-raw'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'


    # Injection explicite du répertoire cible pour FileUploader
    App\Uploader\FileUploader:
        arguments:
            $targetDirectory: '%app.files_dir%'

    # Injection explicite du répertoire cible et des dépendances pour PhotoUploader
    App\Uploader\PhotoUploader:
        arguments:
            $targetDirectory: '%app.photos_dir%'
            $exifExtractor: '@App\Service\ExifExtractor'
            $mimeTypeValidator: '@App\Service\PhotoMimeTypeValidator'
            $directoryManager: '@App\Service\UploadDirectoryManager'
            $fileNameGenerator: '@App\Uploader\DefaultFileNameGenerator'

    App\Service\PhotoMimeTypeValidator:
        arguments:
            $allowedMimeTypes: '%app.photo_allowed_mime_types%'

    App\Service\FileNameGeneratorInterface: '@App\Uploader\DefaultFileNameGenerator'
    App\Uploader\DefaultFileNameGenerator: ~

    App\Service\UploadDirectoryManager: ~

    # Injection explicite du répertoire upload pour FilePathSecurity
    App\Security\FilePathSecurity:
        arguments:
            $uploadDir: '%app.files_dir%'
